### ISSUE TITLE
Demo totally fails in both Edge and IE11

### ISSUE THREAD

**Issue by PeterWone** [aurelia/ui-virtualization#90] opened 2016-12-02 14:38 UTC
**I'm submitting a bug report**

The demo at http://aurelia.io/ui-virtualization/ fails to render on IE11.447 or Microsoft Edge 38.14393.0.0

One item is rendered. You can manage the number of items in the list but the virtual list rendering is totally busted. It works fine on Chrome and Firefox.

**Comment by AStoker** [comment] 2016-12-02 20:06
Are you getting any errors in the console?

**Comment by PeterWone** [comment] 2016-12-02 21:40
Edge? No. IE11? Yes.
The attached object looks okay.
```
HTML1300: Navigation occurred.
ui-virtualization
attached [object HTMLDivElement]
   "attached"
   <div class="au-target" au-target-id="16" element.ref="parentElement"></div>

Potentially unhandled rejection [2] Error: Bootstrap's JavaScript requires jQuery
   at Anonymous function (Unknown script code:3:22621)
   at Anonymous function (Unknown script code:3:22531)
   at i (http://aurelia.io/ui-virtualization/jspm_packages/system.js:4:31560)
   at s (http://aurelia.io/ui-virtualization/jspm_packages/system.js:4:31192)
   at Anonymous function (http://aurelia.io/ui-virtualization/jspm_packages/system.js:4:31647)
   at Anonymous function (Unknown script code:4:27451)
   at i (http://aurelia.io/ui-virtualization/jspm_packages/system.js:4:31560)
   at n (http://aurelia.io/ui-virtualization/jspm_packages/system.js:4:30141)
   at execute (http://aurelia.io/ui-virtualization/jspm_packages/system.js:5:3169)
   at y (http://aurelia.io/ui-virtualization/jspm_packages/system.js:4:9940)
Potentially unhandled rejection [3] TypeError: Unable to get property 'localName' of undefined or null reference
   at a.prototype.createTopBufferElement (Unknown script code:15:12712)
   at b.prototype.attached (Unknown script code:15:16063)
   at a.prototype.attached (Unknown script code:11:3238)
   at a.prototype.attached (Unknown script code:10:14500)
   at a.prototype.attached (Unknown script code:10:18746)
   at a.prototype.attached (Unknown script code:10:14559)
   at a.prototype.attached (Unknown script code:10:18746)
   at Anonymous function (Unknown script code:6:5984)
   at M (http://aurelia.io/ui-virtualization/jspm_packages/system-polyfills.js:4:8723)
   at H (http://aurelia.io/ui-virtualization/jspm_packages/system-polyfills.js:4:8310)
```

**Comment by AStoker** [comment] 2016-12-05 15:12
That looks like a bug in the build process. That's come up on occasion for me, and I think it's related to how the CLI bundles it's files in different orders. I'm not sure what the demo site uses though. But I don't think the issue is related to the virtualization plugin (thankfully).  
It looks like the config file has two separate versions of Bootstrap installed... It might just need to remove one of them.

**Comment by PeterWone** [comment] 2016-12-06 00:59
I see that bootstrap message a lot with CLI apps. If I remember correctly you can make it go away by specifying the jQuery dependence and making the boostrap entry the first item in the dependency section of the aurelia.json file. I don't think bootstrap is the problem because a fault in the build process should cause the same problem on all browsers. At least it seems so to me. 

I started to recreate the demo as a CLI Typescript app because that's where my experience lies, but I've been sidetracked by learning to use faker in an Aurelia app.

**Comment by AStoker** [comment] 2016-12-06 14:02
Could be that perhaps Edge/IE are loading things differently/strangely, which causes this error? 
I've been loaded up with other things, and I lack the time to look at this right now. I do know that the virtualization works in IE and Edge because we use it in our production application. So at least that's good :) Would you have time to look into why this is failing and maybe make a PR?

**Comment by Thanood** [comment] 2016-12-06 18:41
This issue has also been discussed here: https://github.com/aurelia/skeleton-navigation/issues/632
Bottom line seems to be that

> jQuery and Bootstrap just don't play well in a modular setup, unfortunately.

My guess is that there are multiple jQueries or jQuery is not exposed to the `window` (at least not soon enough). In both cases it could be a solution to include jQuery in an "ordinary" `<script>` tag in index.html.

**Comment by PeterWone** [comment] 2016-12-06 23:07
> I do know that the virtualization works in IE and Edge because we use it in our production application. 

I thought that might be so, which is why I worded it "_demo_ totally fails". I've managed to get faker to work with a CLI app, so I will try to clean-room the demo. The way I load faker is truly hideous but all mocks are hacks anyhow, so I can live with it.

**Comment by PeterWone** [comment] 2016-12-07 01:05
I now have a clean room implementation of the demo running on both Edge and IE11. They both flake out after about 50000 items but (a) no sane person would ship a result set that large across the net even in chunks (b) this is a shortcoming of the JS engine in use, not the library. 

My version is CLI with Typescript, do you want it? I have a GitHub identity but no experience with contributing code so if you want me to post the code some guidance will be necessary.

I'm still getting that bootstrap message despite having dependencies declared but it doesn't seem to matter.

**Comment by AStoker** [comment] 2016-12-07 13:53
All browsers have limitations. IE and Edge do seem to hit a limit faster than others in regards to how much data it can actually store. A solution for this would be to remove items from the array as you go down.  

If you want to post the link to your reproducible repo, that'd be helpful. But right now, I don't have time to fix the demo. A fix for your setup would be to just prepend jQuery in the vendor bundle, and don't mark "jQuery" as a dependency anywhere (since it'll already be loaded from the prepend).

**Comment by vegarringdal** [comment] 2017-01-08 22:03
The issue is prb maximum height of a div (issue with large arrays in IE)

http://stackoverflow.com/questions/7719273/determine-maximum-possible-div-height

ie is around 50k when row is 25px, ff is little bit more, chrome is 800k when I tested this on my own grid, its possible to calculate.

**Comment by mKlus** [comment] 2017-07-05 11:01
@PeterWone I wanted to recreate the virtualization in cli project as well to confirm that it works fine in IE11 (In fact in a .Net Application that has an embedded IE WebBrowser Control). But now I found this thread and was wondering if you'd be able to share (zip) your project with me so I can give it some test?

**Comment by PeterWone** [comment] 2017-07-05 12:54
You're in luck. It took a while but I've found it. This zip file is basically the whole project omitting the node_modules folder to keep the size down.

[virt.zip](https://github.com/aurelia/ui-virtualization/files/1124670/virt.zip)

**Comment by mKlus** [comment] 2017-07-05 22:45
@PeterWone Thank you very much! :) It just worked.

The IE11 performance seems much worse then Chrome, though. For example when scrolling down 10000 items using scrollbar the divs become invisible while scrolling and once you release the scrollbar they load. I wonder if it is limitation in IE or bug in aurelia or elsewhere.

**Comment by PeterWone** [comment] 2017-07-05 23:20
If you really want to handle lists with that many items you could re-write ui-virt to let the browser process its message queue more often.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by vegarringdal** [comment] 2017-07-05 23:42
@mKlus @PeterWone 

Using requestAnimationFrame more might help..

Im using it 2 times on my grid on scrolling, think thats what helped me a lot in IE11
Demo link to the new one Im working on/off :-)
https://vegarringdal.github.io/vGridDemo/

click the `push(data) 10 000` to add 10k rows in the demo

Btw, not using ui-vir in this one, but it supports unless scrolling (if you dont go over browser div max height limit)

**Comment by bigopon** [comment] 2019-01-15 22:34
I have now build proper app for demo in IE11 https://dist-rlveytsvzp.now.sh/#/

Note that app for issue 138 isn't displaying text because dynamic template for `<tr/>` as direct child isn't supported in IE11. Though the behavior of infinite scroll next still there

@EisenbergEffect This can be closed

**Comment by bigopon** [comment] 2019-01-15 22:35
Note you can also build the app (after #140 has been merged) by:

```bash
cd sample/sample-v-ui-app
npm install
npm run build
```

Built app will be at dist folder

**Closed as completed** 2019-01-16 00:39 UTC
Labels: bug, question

**Comment by bigopon** [comment] 2019-01-21 01:55
For anyone interested in this, the Readme now there's a link to newly built demo app at https://aurelia-ui-virtualization.now.sh

**Comment by kellyethridge** [comment] 2020-04-23 17:58
Is the demo app at [https://aurelia-ui-virtualization.now.sh/](https://aurelia-ui-virtualization.now.sh/) still supposed to work in IE11? I get an error.

**Comment by bigopon** [comment] 2020-04-23 22:17
@kellyethridge that's weird. thanks for noticing & letting us know. I'll fix it soon.

**Comment by milkshakeuk** [comment] 2021-02-22 09:56
@bigopon did you ever get this fixed?

**Comment by bigopon** [comment] 2021-02-22 16:47
@milkshakeuk I think it's fixed awhile ago. It's working for me without any issues on IE11:
![image](https://user-images.githubusercontent.com/9994529/108740454-cc179900-7589-11eb-896b-374f69e4c20c.png)

Are you getting any errors?
