### ISSUE TITLE
Rough scrolling and broken styles with table

### ISSUE THREAD

**Issue by Sayan751** [aurelia/ui-virtualization#138] opened 2018-12-20 13:37 UTC
**I'm submitting a bug report**

* **Library Version:**
1.0.0-beta.3.3.2

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
10.13.0

* **NPM Version:**
6.0.1

* **JSPM OR Webpack AND Version**
webpack 4.28.0

* **Browser:**
Chrome 71.x | Firefox 64.x 

* **Language:**
TypeScript 3.2.2

**Current behavior:**
I have tried infinite scrolling with this package.  As user scrolls down, I am adding 30 (chunk size) new items in the array. I have tried this on a normal bootstrap table and a table custom control (also based on bootstrap). In both the cases, I noticed similar problems:

1. The scrolling in Chrome is too rough. The scrollbar as well as the table jumps to often, which results in a jerky scrolling. Sometimes, rows (and columns) expand/collapse automatically (without any explicit/intended user interaction apart from scrolling).
1. Another major problem is that it breaks the style.

To demonstrate the problem I have created a repo: https://github.com/Sayan751/au-virtualization-demo
The repo also has some demo gifs that show the problem: 
* [custom control](https://github.com/Sayan751/au-virtualization-demo/blob/master/problem-demo_custom%20control.gif)
* [table](https://github.com/Sayan751/au-virtualization-demo/blob/master/problem-demo_table.gif)

The screen captures are done on Chrome. The scrolling is somewhat better with Firefox, but it too has the problem with styling.

**Expected/desired behavior:**

* **What is the expected behavior?**
Smooth scrolling is expected that also keeps the styling intact.

* **What is the motivation / use case for changing the behavior?**
Better user experience.

**Comment by bigopon** [comment] 2019-01-14 11:59
I have tested this issue against my latest commit. I couldn't reproduce it manually by scrolling up and down, so I'm not sure if I fixed it, or reproduced it incorrectly. @Sayan751 Would be nice if you could have a check and confirm. Demo app at https://dist-owjyzhcvev.now.sh/#/issue-138

**Comment by bigopon** [comment] 2019-01-14 12:00
@Sayan751 Also can you help describe styling issue that you encountered?

**Comment by Sayan751** [comment] 2019-01-15 07:03
@bigopon The problem with scrolling seems to be resolved in the the demo app. I will try to clone this repo and test the changes locally once. 

The main problem that I had with styling is that for a striped table, sometimes the stripes are not applied at all, and all the rows will appear to have same style. That problem seems to be mostly resolved in your demo app. There is a minor glitch, where a light row becomes gray on scroll or vice versa. Not sure if that can be handled, as the browser will continue to apply the styles as per the CSS rules defined. When the DOM objects are removed, `n+1`th row become `n`th row and with that changes the effective CSS rules applied on the row. 

It would be superb if you find a way to deal with that. If that is not possible, then maybe it is a good idea to add that as limitation in documentation.

**Comment by bigopon** [comment] 2019-01-15 21:12
@Sayan751 I'm not sure what can be done to deal with striped table, I think it's easier to employ css class based on `$index` and document them as workaround.

**Comment by rowellx68** [comment] 2019-02-13 14:22
Similar  to the one suggested by @bigopon, we used the `$odd` to create classes.

```html
<table>
  <tbody>
    <tr virtual-repeat.for="item of items" class="row-item-${$odd ? 'odd' : 'even'}">
      <td>${item.name}</td>
    </tr>
  </tbody>
</table>
```

**Comment by bigopon** [comment] 2019-02-13 20:53
@rowellx68 Cool, thanks for jumping in, may I know if you are using latest version? If so, is it behaving as intended as you seem to be using it on table repeating as well. Which I think I should get 1 more confirmation before asking @EisenbergEffect or @Sayan751 to close this issue.

**Comment by Sayan751** [comment] 2019-02-14 09:25
@bigopon At this point it is bit difficult for me to confirm the changes as we moved little bit away from the continuous scrolling. Feel free to close this issue if others confirm.

**Comment by rowellx68** [comment] 2019-02-20 10:12
@bigopon We are using version `*1.0.0-beta.4`. We are however experiencing a different [issue ](https://github.com/aurelia/ui-virtualization/issues/146) now.

**Closed as completed** 2019-02-23 05:28 UTC
